### ISSUE TITLE
Global hotkeys

### ISSUE THREAD

**Issue by VlaK0r** [ttsping/foo_flowin#1]
Hello!
I observe strange behavior when using global hotkeys. For example, the global hotkey "show" is set. If the foobar2000 is in the foreground, then everything works fine. If the player is in the background, then the window does not appear or disappear. But this option turns on and off.
Sorry for my English.

**Comment by ttsping** [comment]
need more details. can't reproduce on my machine.

**Comment by ASopH** [comment]
Hi, I hope I can help you!
With this configuration, the pictures in flowin are not automatically updated when I select another album/artist. 
![Config](https://user-images.githubusercontent.com/14108704/124144609-69309400-da8c-11eb-9da0-4765749ee33e.png)
This flowin contains 4 pictures (Front;Back;CD and Artist). After I unShow and Show this flowin I can see the right select album art...
I hope it helps :-)
thank you for your help

**Comment by VlaK0r** [comment]
Unfortunately, I don’t know how best to explain
