### ISSUE TITLE
request: 64bit-componet

### ISSUE THREAD

**Issue by ASopH** [ttsping/foo_flowin#4]
Hi,

is there a chance to get a 64bit compile for the new fb2k 64bit-version? 
thanks

**Comment by ttsping** [comment]
https://github.com/ttsping/foo_flowin/releases/tag/0.2.0

not fully tested.

**Comment by ASopH** [comment]
you're great :-) - I'll test it, thank you!!

**Comment by ASopH** [comment]
ok, Installing the component is a little bit tricky :-) - DLL's where in subfolders, so fb2k don't see them

**Comment by ASopH** [comment]
Hi, sorry for late reply - I've fully tested and found no errors (except my last reply)
good job thx

**Comment by ASopH** [comment]
Hi, thank you for the update, I'd no issues... 
If you are satisfied, this can be closed here - great job!
