### ISSUE TITLE
Foobar v2

### ISSUE THREAD

**Issue by Hamybal** [ttsping/foo_flowin#5]
First of all thank you for this component I've been using for so long and makes things so much better!

Flowin is still working in the new version of foobar v2 (32 bit) only there are 2 issues.
1. enabling/disabling "show on startup/always on top" doesn't seem to matter because flowin will always be open on startup aswell as being on top.
2. With the old stable version keybinding on "Show" could either open and close the flowin, but with the version foobar it will only open and can't close it.

I've been testing and as far as I can see these are the only things that don't work.

Sorry for bothering you, I'm not sure if you are still working on the component and if that is the case it's totally understandable.
Furthermore I wish you a great day!

**Comment by ttsping** [comment]
https://github.com/ttsping/foo_flowin/releases/tag/0.2.0

not fully tested.

**Comment by Hamybal** [comment]
You're a god that was real quick!

Something still seems inconsistent with 3 differents flowin all have different outcomes.
first one to open was perfectly fine and works as it should be.
second one doesn't open at all unless done mannually and click show.
and the third one can open but cannot close while all settings for them all are the same.
https://imgur.com/a/Z2nTwFq

I've always used playlist organiser by itself and never lagged, but tried doing it with flowin today and I just had to delete the flowin because it just couldn't handle to many playlists and kept freezing plus foobar itself.
Not sure if this can be fixed because this includes another component but because it works without flowin there might be some reason to why.

Also it might not even the problem of flowin because foobar v2 is in beta itself.
Once again many thanks for the component and your quick response it's all really appreciated ;)

**Comment by ttsping** [comment]
> 

https://github.com/ttsping/foo_flowin/releases/tag/0.2.1
